#!/usr/bin/env python
#	vim:fileencoding=utf-8
# (c) 2013 Michał Górny <mgorny@gentoo.org>
# Released under the terms of the 2-clause BSD license.

from gentoopm import get_package_manager
from gentoopm.basepm.atom import PMAtom
from gentoopm.exceptions import EmptyPackageSetError

from gpyutils.ansi import ANSI
from gpyutils.eclasses import guess_package_type, PkgType
from gpyutils.packages import group_packages

import optparse, sys

pm = get_package_manager()

def group_packages_if(pkgs, cond, **kwargs):
	if cond:
		for pg in group_packages(pkgs, **kwargs):
			yield pg
	else:
		for p in pkgs:
			yield [p]

def process(pkgs, output, assume_r1=False, list_all=False):
	sys.stderr.write('%s%sWaiting for PM to start iterating...%s\r'
			% (ANSI.clear_line, ANSI.brown, ANSI.reset))

	for pg in group_packages_if(pkgs, list_all):
		p = pg[-1]
		sys.stderr.write('%s%s%-56s%s (%s%4d%s found)\r'
				% (ANSI.clear_line, ANSI.green, p, ANSI.reset,
					ANSI.white, len(output), ANSI.reset))

		def check_dep(dep, depth = 0, was_first = [True],
				curr_pkg = p):
			if isinstance(dep, PMAtom):
				if dep.blocking:
					return
				for p2 in output.keys():
					if p2 in dep:
						# avoid infinite loops
						output[p2] += 1
						return

				# USE deps cause problems with matching, strip them
				# Note to self: this is ugly.
				dep = pm.Atom(str(dep).partition('[')[0])

				try:
					dep_pkg = pm.repositories['gentoo'].select(dep)
				except EmptyPackageSetError:
	#				print('%s: no package matches %s' % (p, dep))
					return

				dep_t = guess_package_type(dep_pkg)
				if isinstance(dep_t, PkgType.python_r0):
					# in case stdout & stderr goes to the same console,
					# clean up the line before printing
					sys.stderr.write('%s\r' % ANSI.clear_line)

					if was_first[0]:
						print('%s' % p)
						was_first[0] = False
					print('%s%s' % ('    ' * (depth + 1), dep))

					# depscan takes a while, so re-output status
					sys.stderr.write('%s%s%-56s%s (%s%4d%s found)\r'
							% (ANSI.clear_line, ANSI.green, p, ANSI.reset,
								ANSI.white, len(output), ANSI.reset))

					output[dep_pkg] = 1

					for d in (dep_pkg.run_dependencies,
							dep_pkg.build_dependencies,
							dep_pkg.post_dependencies):
						check_dep(d, depth + 1, was_first, dep_pkg)
			else:
				for dp in dep:
					check_dep(dp, depth, was_first, curr_pkg)

		t = guess_package_type(p, check_deps=list_all)
		if list_all and isinstance(t, PkgType.python_r0):
			check_dep(p, depth=-1, was_first=[False])
		if not assume_r1 and not isinstance(t, PkgType.python_r1):
			continue

		for d in (p.run_dependencies, p.build_dependencies, p.post_dependencies):
			check_dep(d)

	sys.stderr.write('%s%sDone.%s\n'
			% (ANSI.clear_line, ANSI.white, ANSI.reset))

def main(prog_name, *argv):
	opt = optparse.OptionParser(
		prog = prog_name,
		usage = '%prog [<packages>...]')
	opt.add_option('-a', '--all',
			dest='list_all', default=False, action='store_true',
			help='List all non-converted packages, not only deps of -r1 packages')
	opt.add_option('-r', '--repo',
			dest='repo', default='gentoo',
			help='Work on given repository (default: gentoo)')
	vals, argv = opt.parse_args(list(argv))

	output = {}

	sys.stderr.write('[note: each package is listed at most once]\n')

	if not argv:
		process(pm.repositories[vals.repo], output, list_all=vals.list_all)
	else:
		for pkg in argv:
			process(pm.repositories[vals.repo].filter(pkg), output, assume_r1=True)

	print('Statistics:')
	for p, count in sorted(output.items(), key=lambda x: x[1]):
		print(' %4d %s' % (count, p))

	return 0

if __name__ == '__main__':
	sys.exit(main(*sys.argv))
