#!/usr/bin/env python
#	vim:fileencoding=utf-8
# (c) 2013 Michał Górny <mgorny@gentoo.org>
# Released under the terms of the 2-clause BSD license.

from gentoopm import get_package_manager

from gpyutils.ansi import ANSI
from gpyutils.implementations import implementations, get_python_impls
from gpyutils.packages import group_packages

import sys

pm = get_package_manager()

keys = [i.short_name for i in implementations]

def process(pkgs):
	for pg in group_packages(pkgs.sorted, 'slotted_atom'):
		print('%s%s%s' % (ANSI.white, pg[0].slotted_atom, ANSI.reset))
		for p in pg:
			output = [' ' * len(x) for x in keys]

			impls = get_python_impls(p)
			if impls is None:
				# not a python package
				continue
			for i in impls:
				output[keys.index(i.short_name)] = ('%s%s%s'
					% (i.status.color, i.short_name, ANSI.reset))

			print('%16s: %s' % (p.version, ' '.join(output)))

def main(prog_name, *packages):
	if not packages:
		sys.stderr.write('Usage: %s <atom>...\n' % prog_name)
		return 1

	for pkg in packages:
		process(pm.repositories['gentoo'].filter(pkg))

	return 0

if __name__ == '__main__':
	sys.exit(main(*sys.argv))
