#!/usr/bin/env python

from gentoopm import get_package_manager
from gentoopm.basepm.atom import PMAtom
from gentoopm.exceptions import EmptyPackageSetError

from gpyutils.ansi import ANSI

import sys

pm = get_package_manager()

class PkgType(object):
	class other(object):
		def __gt__(self, other):
			return False

	class python(object):
		def __gt__(self, other):
			return other is PkgType.other

	class python_r1(object):
		def __gt__(self, other):
			return True

	def __new__(cls, pkg, curr_pkg = None):
		# excludes
		if pkg.key in ('dev-lang/python',
				'dev-python/pypy',
				'dev-java/jython'):
			return cls.other

		if curr_pkg is not None:
			if 'git-2' in curr_pkg.inherits and pkg.key == 'dev-vcs/git':
				return cls.other
			elif 'subversion' in curr_pkg.inherits and pkg.key == 'dev-vcs/subversion':
				return cls.other

		if 'python-r1' in pkg.inherits:
			return cls.python_r1
		elif 'python-single-r1' in pkg.inherits:
			return cls.python_r1
		elif 'python' in pkg.inherits:
			return cls.python
		else:
			return cls.other

output = {}

print('[note: each package is listed at most once]')

def process(pkgs, assume_r1 = False):
	sys.stderr.write('%s%sWaiting for PM to start iterating...%s\r'
			% (ANSI.clear_line, ANSI.brown, ANSI.reset))

	total_need = 0

	for p in pkgs:
		sys.stderr.write('%s%s%-56s%s (%s%4d%s found)\r'
				% (ANSI.clear_line, ANSI.green, p, ANSI.reset,
					ANSI.white, total_need, ANSI.reset))

		t = PkgType(p)
		if not assume_r1 and t is not PkgType.python_r1:
			continue

		def check_dep(dep, depth = 0, was_first = [True], curr_pkg = p):
			if isinstance(dep, PMAtom):
				if dep.blocking:
					return
				for p2 in output.keys():
					if p2 in dep:
						# avoid infinite loops
						output[p2] += 1
						return

				# USE deps cause problems with matching, strip them
				# Note to self: this is ugly.
				dep = pm.Atom(str(dep).partition('[')[0])

				try:
					dep_pkg = pm.stack.select(dep)
				except EmptyPackageSetError:
	#				print('%s: no package matches %s' % (p, dep))
					return

				if PkgType(dep_pkg, curr_pkg) is PkgType.python:
					# in case stdout & stderr goes to the same console,
					# clean up the line before printing
					sys.stderr.write('%s\r' % ANSI.clear_line)

					if was_first[0]:
						print('%s' % p)
						was_first[0] = False
					print('%s%s' % ('    ' * (depth + 1), dep))

					# depscan takes a while, so re-output status
					sys.stderr.write('%s%s%-56s%s (%s%4d%s found)\r'
							% (ANSI.clear_line, ANSI.green, p, ANSI.reset,
								ANSI.white, total_need, ANSI.reset))

					output[dep_pkg] = 1

					for d in (dep_pkg.run_dependencies,
							dep_pkg.build_dependencies,
							dep_pkg.post_dependencies):
						check_dep(d, depth + 1, was_first, dep_pkg)
			else:
				for dp in dep:
					check_dep(dp, depth, was_first, curr_pkg)

		for d in (p.run_dependencies, p.build_dependencies, p.post_dependencies):
			check_dep(d)

	sys.stderr.write('%s%sDone.%s\n'
			% (ANSI.clear_line, ANSI.white, ANSI.reset))

if len(sys.argv) == 1:
	process(pm.repositories['gentoo'])
else:
	for pkg in sys.argv[1:]:
		process(pm.stack.filter(pkg), True)

print('Statistics:')
for p, count in sorted(output.items(), key = lambda x: x[1]):
	print(' %4d %s' % (count, p))
